
package de.wsdl.ticketEckert;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketauftragService", targetNamespace = "http://service.ticketeckert.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketauftragService {


    /**
     * 
     * @param tickets
     * @return
     *     returns java.util.List<de.wsdl.ticketEckert.Ticket>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erstelleTickets", targetNamespace = "http://service.ticketeckert.de/", className = "de.wsdl.ticketEckert.ErstelleTickets")
    @ResponseWrapper(localName = "erstelleTicketsResponse", targetNamespace = "http://service.ticketeckert.de/", className = "de.wsdl.ticketEckert.ErstelleTicketsResponse")
    public List<Ticket> erstelleTickets(
        @WebParam(name = "Tickets", targetNamespace = "")
        List<Ticket> tickets);

    /**
     * 
     * @param ticket
     * @return
     *     returns de.wsdl.ticketEckert.Ticket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erstelleTicket", targetNamespace = "http://service.ticketeckert.de/", className = "de.wsdl.ticketEckert.ErstelleTicket")
    @ResponseWrapper(localName = "erstelleTicketResponse", targetNamespace = "http://service.ticketeckert.de/", className = "de.wsdl.ticketEckert.ErstelleTicketResponse")
    public Ticket erstelleTicket(
        @WebParam(name = "Ticket", targetNamespace = "")
        Ticket ticket);

}
